### ISSUE TITLE
Unknown import path

### ISSUE THREAD

**Issue by kamronbatman** [amyangfei/redlock-go#3]
I am new to Go modules, so please let me know if I am doing something wrong.
I enabled modules, then did a go get. It said it could not find the main package.
This also happens if I do not have modules enabled.
So I went to the package src and did `go install` and I got this.
```
can't load package: package github.com/amyangfei/redlock-go: unknown import path "github.com/amyangfei/redlock-go": cannot find module providing package github.com/amyangfei/redlock-go
```

Am I missing a step or have modules changed for v1.11?

**Comment by kamronbatman** [comment]
Upgrading from 1.11.5 to 1.12 fixed it.

**Comment by amyangfei** [comment]
Go modules is turned off in go1.11 by default, when we execute `go get github.com/amyangfei/redlock-go/redlock`, it simply downloads the library to `$GOPATH/src/github.com/amyangfei/redlock-go`.

If we turn on the GO modules via `export GO111MODULE=on`, we can execute `go get github.com/amyangfei/redlock-go` in a module's root directory which contains a `go.mod` file and `go.sum` file. After that `github.com/amyangfei/redlock-go` will be added to `go.mod` and `go.sum` will be updated at the same time.
