### ISSUE TITLE
NewSimpleCache is leaking goroutines

### ISSUE THREAD

**Issue by OlivierArbey** [amyangfei/redlock-go#5]
NewSimpleCache is leaking goroutines because there is no mechanism to cancel its context.

**Comment by amyangfei** [comment]
Thanks for your feedback, this commit fixed this issue, the gc background goroutine can be canceled now, https://github.com/amyangfei/redlock-go/commit/a5fc556917fc520155e82d23a2cfce576ad79f2b.
The new API is available from v3.0.0.
Close this issue now, feel free to reopen it if you have any more problem with it.
